config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :tshirts
  resources :tshirts
  root 'tshirts#index'

end

app/models/tshirt.rb
class Tshirt < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tshirts_controller.rb
class TshirtsController < ApplicationController

  before_action :authenticate_user!, only: [:edit, :create, :update, :destroy]

  def index
    @tshirts = Tshirt.all
  end

  def new
    @tshirt = Tshirt.new
  end

  def show
    @tshirt = Tshirt.find( params[:id] )
  end

  def edit
    @tshirt = Tshirt.find( params[:id] )
  end

  def create
    @tshirt = Tshirt.new(tshirt_params)
    if @tshirt.save
      redirect_to @tshirt
    end
  end

  def update
    @tshirt = Tshirt.find( params[:id] )
    if @tshirt.update(tshirt_params)
      redirect_to @tshirt
    end
  end

  def destroy
    @tshirt = Tshirt.find( params[:id] )
    @tshirt.destroy
    redirect_to tshirts_url
  end

  private

  def tshirt_params
    params.require(:tshirt).permit(:title, :photo_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tshirts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <h1><%= link_to 'ts', tshirts_path %></h1>
  <%= link_to 'New Tshirt', new_tshirt_path %>
</header>
<% unless user_signed_in? %>
	<h3><%= link_to "Sign In", new_user_session_path %></h3>
	<h3><%= link_to "Sign Up", new_user_registration_path %></h3>
<% else %>
	<h2>Hello, <%= link_to current_user.email %></h2>
	<h3><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></h3>
<% end %>

<%= yield %>

</body>
</html>

app/views/tshirts/_form.html.erb
<%= form_for(@tshirt) do |f| %>
  <% if @tshirt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tshirt.errors.count, "error") %> prohibited this tshirt from being saved:</h2>

      <ul>
      <% @tshirt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :photo_url %><br>
    <%= f.text_field :photo_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tshirts/edit.html.erb
<div class='g-1-3'>
  <div class='tshirt'>
    <h1>Editing tshirt</h1>
    <%= render 'form' %>
    <%= link_to 'Show', @tshirt %> |
    <%= link_to 'Back', tshirts_path %>
  </div>
</div>

app/views/tshirts/index.html.erb
<% @tshirts.each do |t| %>
  <div class='g-1-3'>
    <div class='tshirt'>
      <h2><%= t.title %></h2>
      <%= image_tag( t.photo_url )%>
      <%= link_to 'view', tshirt_path(t) %>
      <%= link_to 'edit', edit_tshirt_path(t) %>
      <%= link_to 'delete', t, method: :delete %>
    </div>
  </div>
<% end %>

app/views/tshirts/new.html.erb
<div class='g-1-3'>
  <div class='tshirt'>
    <h1>New tshirt</h1>
    <%= render 'form' %>
    <%= link_to 'Back', tshirts_path %>
  </div>
</div>

app/views/tshirts/show.html.erb
<div class='g-1-3'>
  <div class='tshirt'>
    <h2><%= @tshirt.title %></h2>
    <%= image_tag( @tshirt.photo_url )%>
    <%= link_to 'Edit', edit_tshirt_path(@tshirt) %>
    <%= link_to 'delete', @tshirt, method: :delete %>
  </div>
</div>